CREATE TABLE Players (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Matches (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Player1 INT NOT NULL,
    Player2 INT NOT NULL,
    Winner INT NOT NULL,
    FOREIGN KEY (Player1) REFERENCES Players(ID),
    FOREIGN KEY (Player2) REFERENCES Players(ID),
    FOREIGN KEY (Winner) REFERENCES Players(ID),
    CHECK((Player1 <> Player2) AND ((Winner = Player1) OR (Winner = Player2)))
);